@hostname = localhost
@port = {{$dotenv PORT}}
@host = {{hostname}}:{{port}}
@contentType = application/json
@authToken = {{login.response.body.token}}

###

# @name checkHealth
GET http://{{host}}/health HTTP/1.1

###

# @name getUsers
GET http://{{host}}/users HTTP/1.1

###
# @prompt userId Id of the user to get

# @name getUser
GET http://{{host}}/users/{{userId}} HTTP/1.1

###
# @prompt email Email of the user
# @prompt password Password of the user

# @name signup
POST http://{{host}}/signup HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
# @prompt email Email of the user
# @prompt password Password of the user

# @name login
POST http://{{host}}/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###

# @name getFunds
GET http://{{host}}/funds HTTP/1.1
Authorization: Bearer {{authToken}}

###
# @prompt fundId Id of the fund to get

# @name getFund
GET http://{{host}}/funds/{{fundId}} HTTP/1.1
Authorization: Bearer {{authToken}}

###
# @prompt name Name of the fund
# @prompt balance Balance of the fund

# @name createFund
POST http://{{host}}/funds HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "name": "{{name}}",
    "balance": "{{balance}}"
}

###
# @prompt fundId Id of the fund
# @prompt name Name of the fund
# @prompt balance Balance of the fund

# @name updateFund
PUT http://{{host}}/funds/{{fundId}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "name": "{{name}}",
    "balance": "{{balance}}"
}


###
# @prompt fundId Id of the fund

# @name deleteFund
DELETE http://{{host}}/funds/{{fundId}} HTTP/1.1
Authorization: Bearer {{authToken}}
